apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lab-management
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts: [lab.wuosu.xyz]
      secretName: lab-wuosu-tls
  rules:
    - host: lab.wuosu.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
